#!/usr/bin/env python

import re
import os
import gitlab
import csv
import warnings
import yaml
import json
import argparse
from requests.packages.urllib3.exceptions import InsecureRequestWarning


class GitLabProject(object):
    def __init__(self, project):
        self.api = project

    def has_gitlab_ci(self):
        tree = self.api.repository_tree(ref=self.api.default_branch, recursive=False)
        filenames = [item['name'] for item in tree if item['type'] == 'blob']    
        return next((name for name in filenames if name.lower() == ".gitlab-ci.yml" or name.lower() == ".gitlab-ci.yaml"), None)

    def get_ci_content(self):
        file_content = self.api.files.get(file_path='.gitlab-ci.yml', ref=self.api.default_branch)
        content_decoded = file_content.decode().decode('utf-8')
        return yaml.safe_load(content_decoded)

    def get_include(self, key, pattern):
        ci = self.get_ci_content()
        return next((i for i in ci.get('include', []) if key in i and pattern.match(i[key])), None)

    def includes_library(self, lib, default_branch):
        if not self.has_gitlab_ci(): return False

        ci = self.get_ci_content()
        yaml_url = re.compile(rf".*/{lib}/.+\.ya?ml")
        project_ref = re.compile(lib)
        include_str = ci.get('include') if isinstance(ci.get('include'), str) and yaml_url.match(ci.get('include')) else None
        include_p = self.get_include('project', project_ref)
        include_e = self.get_include('remote', yaml_url)

        if include_str or include_e:
            ref = default_branch
        elif include_p:
            ref = include_p.get('ref', default_branch)
        else: return False
        return {
            'reference': f'{self.api.path_with_namespace}/.gitlab-ci.yml',
            'include': {
              'name': lib,
              'ref': ref,
              'default_ref': ref == default_branch,
              'last_run': self.last_run()
            }
        }

    def last_run(self):
        try:
            pipeline = self.api.pipelines.latest()
            return pipeline.created_at
        except Exception as e:
            return "No pipelines found"

class GitlabCI_Ref(object):
    def __init__(self, shared_ci, gl, **kwargs):
        self.dependant_projects = {}
        self.shared_ci = shared_ci
        self.gl = gl
        self.project = self.gl.projects.get(self.shared_ci)
        self.kwargs = kwargs
        self.verbose = kwargs.get('verbose', False)
    
    def log_error(self, msg):
        print(f'\033[91m{msg}\033[0m')
    def log(self, msg, *, color=''):
        print(f'{color}{msg}\033[0m')


    def search(self, path):
        if len(path) > 0:
            group = self.gl.groups.get(path)
            projects = group.projects.list(include_subgroups=True, get_all=True)
        else:
            projects = self.gl.projects.list(get_all=True)

        total_projects = len(projects)
        index = 0
        for project_list_object in projects:
            index += 1
            i = f'({index}/{total_projects})'
            # We need the full project object to access the repository tree/files
            project = GitLabProject( self.gl.projects.get(project_list_object.id) )
            if project.api.archived:
                if self.verbose:
                    self.log(f'{i} [archived - skipping] {project.api.path_with_namespace}')
                continue
            try: 
                reference = project.includes_library(self.shared_ci, self.project.default_branch)
                if reference:
                    self.dependant_projects[project.api.path_with_namespace] = reference
                    if self.verbose:
                        self.log(f'{i} [in-use] {project.api.path_with_namespace}', color='\033[96m')
                elif self.verbose:
                    self.log(f'{i} [no dependency] {project.api.path_with_namespace}')
            except yaml.parser.ParserError as e:
                self.log_error(f"{i} [ERROR] failed to parse .gitlab-ci.yml for {project.api.path_with_namespace}")
            except Exception as e:
                self.log_error(f"{i} [ERROR] failed to process {project.api.path_with_namespace}")


    

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description='''
            Search GitLab to find what projects are referencing a particular project/library from
            their .gitlab-ci.yml pipeline configuration.''')
    parser.add_argument('library', help='project path for library')
    parser.add_argument('search', nargs='?', default="",  help='search path / group folder for scanning projects')
    parser.add_argument('--gitlab-url', help='gitlab url', default=os.environ.get('GITLAB_URL'))
    parser.add_argument('--no-ssl-verify', action='store_true', default=False)
    parser.add_argument('--token', default=os.environ.get('GITLAB_ACCESS_TOKEN'), help='uses environment variable GITLAB_ACCESS_TOKEN by default')
    parser.add_argument('--verbose', default=False, action='store_true')
    parser.add_argument('-o', '--out-file', help='write final strucured output to file instead of STDOUT. default format is yaml (for json provide -j flag)')
    parser.add_argument('-j', '--json', default=False, action='store_true', help='format final strucured output as json')
    

    args = parser.parse_args()
    if args.no_ssl_verify:
        warnings.simplefilter('ignore', InsecureRequestWarning)

    gl = gitlab.Gitlab(args.gitlab_url, private_token=args.token, ssl_verify=not args.no_ssl_verify)
    ci = GitlabCI_Ref(args.library, gl, verbose=args.verbose) 
    ci.search(args.search)
    
    if args.json:
        output = json.dumps(ci.dependant_projects, indent=4)
    else:
        output = yaml.dump(ci.dependant_projects)

    if args.out_file:
        with open(args.out_file, 'w') as f:
            f.write(output)
    else:
        print(output)
